ALTER TABLE agents ADD COLUMN IF NOT EXISTS agency_name TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS agency_address TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS dts_license BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS dts_license_number TEXT;
